[sources.sql_database.credentials]
drivername = "postgresql+psycopg2"
database = "active_db"
username = "postgres"
password = "postgres"
host = "postgres_active"
port = 5434

[destination.postgres.credentials]
password = "postgres"
