[sources.sql_database.credentials]
drivername = "mssql+pyodbc"
database = "AdventureWorks2016"
username = "ANALYZER"
password = "ANALYZER"
host = "192.168.1.141"
port = 1433

[sources.sql_database.credentials.query]
driver = "ODBC Driver 18 for SQL Server"
TrustServerCertificate = "yes"

[destination.postgres.credentials]
password = "postgres"
