#!/usr/bin/env bash
#
# Generate a .env for this stack with strong random secrets, and make sure the
# dlt secrets files exist (they are git-ignored).
#
# Usage:
#   ./scripts/generate-env.sh            # create .env (refuses to overwrite)
#   ./scripts/generate-env.sh --force    # overwrite an existing .env
#
# The SQL Server credentials are NOT generated: they belong to your own SQL
# Server. Fill them into
#   dlt/pipelines/sqlserver_to_postgres/.dlt/secrets.toml
# after running this script.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$root/.env"
force=0
[ "${1:-}" = "--force" ] && force=1

if [ -f "$env_file" ] && [ "$force" -ne 1 ]; then
    echo "ERROR: $env_file already exists (use --force to overwrite)." >&2
    exit 1
fi

# Fernet keys are urlsafe-base64 of 32 bytes; openssl's base64 is compatible
# after the URL-safe alphabet substitution.
fernet_key="$(openssl rand -base64 32 | tr '+/' '-_')"
hex() { openssl rand -hex 32; }

umask 077
cat > "$env_file" <<EOF
# Generated by scripts/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not commit this file (.gitignore covers .env).

AIRFLOW_ADMIN_USER=admin
AIRFLOW_ADMIN_PASSWORD=$(hex)
AIRFLOW_FERNET_KEY=$fernet_key
AIRFLOW_WEBSERVER_SECRET_KEY=$(hex)
AIRFLOW_API_AUTH__JWT_SECRET=$(hex)
SUPERSET_SECRET_KEY=$(hex)
SUPERSET_ADMIN_USER=admin
SUPERSET_ADMIN_PASSWORD=$(hex)
# Metabase needs a 16/24/32-char key, so 16 bytes of hex (32 chars), not 32.
METABASE_SECRET_KEY=$(openssl rand -hex 16)
POSTGRES_PASSWORD=$(hex)
DEBEZIUM_PASSWORD=$(hex)
CLICKHOUSE_PASSWORD=$(hex)

POSTGRES_PORT=5433
POSTGRES_ACTIVE_PORT=5434
AIRFLOW_PORT=8080
SUPERSET_PORT=8089
SUPERSET_MCP_PORT=5008
METABASE_PORT=3001
KAFKA_CONNECT_PORT=8083
KAFKA_UI_PORT=8081
CLICKHOUSE_HTTP_PORT=8123
CLICKHOUSE_NATIVE_PORT=9000
EOF
chmod 600 "$env_file"
echo "wrote $env_file"

# --- dlt secrets: .env owns the Postgres password, so the destination password
# is intentionally left out of these files. --------------------------------
pg_secrets="$root/dlt/pipelines/postgres_active_to_postgres/.dlt/secrets.toml"
mssql_secrets="$root/dlt/pipelines/sqlserver_to_postgres/.dlt/secrets.toml"

if [ ! -f "$pg_secrets" ]; then
    echo "NOTE: $pg_secrets is missing; create it from secrets.toml.example"
    echo "      (the Postgres password comes from .env, no need to set it there)."
fi
if [ ! -f "$mssql_secrets" ]; then
    echo "NOTE: $mssql_secrets is missing; create it from secrets.toml.example and"
    echo "      fill in the real SQL Server host/login/password."
fi

echo
echo "Next: docker compose up -d --build"
